version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: elderco
      POSTGRES_USER: crmuser
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crmuser -d elderco"]
      interval: 5s
      timeout: 5s
      retries: 10


  web:
    build: .
    command: gunicorn dcrm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "manage.py", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 6

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    environment:
      - DJANGO_API_URL=http://web:8000
    ports:
      - "3000:3000"
    depends_on:
      web:
        condition: service_healthy

volumes:
  postgres_data: